version: '3.8'
services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: steeldoor
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - ./db/start_db.sql:/docker-entrypoint-initdb.d/init.sql:z
    networks:
      - steeldoor
  api:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build: ApiSteelDoor
    ports:
      - 8080:8080
    networks:
      - steeldoor
  frontend:
    restart: always
    depends_on:
      - api
    build: frontend
    ports:
      - 4200:4200
    networks:
      - steeldoor
volumes:
  db:
    driver: local
networks:
  steeldoor: